### ISSUE TITLE
TC_INSTRUCTOR_6 > LMS: INSTRUCTOR: MEMBERSHIP > Pages and Resources page throws Page not found error

### ISSUE THREAD

**Issue by ziafazal** [openedx/build-test-release-wg#182] opened 2022-05-26 11:22 UTC
While testing INSTRUCTOR -> MEMBERSHIP -> Group Community TA role we need to setup [divided discussion](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/manage_discussions/set_up_divided_discussions.html#setting-up-divided-discussions) and that needs to be done via Studio -> Pages and Resources which throws page not found error
**Steps to reproduce:**

1. Got studio
2. Create a course
3. Click on the newly created course
4. Click on Content->Pages and Resources

**Expected result:**
Pages and Resources page should appear
Actual result:
Page not found error appears

**Comment by ziafazal** [comment] 2022-05-26 11:22
label: nutmeg testing

**Comment by Carlos-Muniz** [comment] 2022-05-27 14:18
I have recreated this issue. And will be working on solving this bug.
@ziafazal @BbrSofiane

**Comment by Carlos-Muniz** [comment] 2022-05-27 16:03
The missing pages may be related to the [Discussions MFE not being part of the default MFEs loaded by the sandbox](https://github.com/overhangio/tutor-mfe/blob/3fde4717cdb6b14c12887deeb53ae1ccddf9bf23/tutormfe/plugin.py#L16-L48). I believe it is the [Discussions MFE that manages the Pages & Resources](https://github.com/openedx/edx-platform/blob/d04ba92ead5ada8603d8e680888129710cac9883/cms/djangoapps/contentstore/utils.py#L173).

**Comment by sambapete** [comment] 2022-05-27 17:45
I was trying to reproduce this issue on my own instance with Nutmeg and I couldn't because I do have the forum plugins enabled. That explains it.

**Comment by sambapete** [comment] 2022-05-27 18:19
But @Carlos-Muniz are we talking about the "brand new" Discussions MFE that is still in development or the "old" forum plugin in Tutor? I have a doubt now because I disabled the "old" forum plugins and I am still able to create pages after stopping and restarting Tutor.

I have to note that it still displays "Pages" on my system and not "Pages and Resources".

**Comment by Carlos-Muniz** [comment] 2022-05-27 19:15
@sambapete Based on the code in here: https://github.com/openedx/edx-platform/blob/d04ba92ead5ada8603d8e680888129710cac9883/openedx/core/djangoapps/discussions/config/waffle.py#L1
I'm pretty sure it comes from the discussions MFE that is still in development.

**Comment by regisb** [comment] 2022-05-30 13:14
@Carlos-Muniz You do mean the course authoring MFE, and not the discussions MFE, right? Why would the discussion MFE govern the presence of the "pages and resources" tab in the studio?

**Comment by sarina** [comment] 2022-05-31 14:06
@regisb I actually think Carlos is right on this. The new "Pages and Resources" view was developed in tandem with the new Discussions MFE. It includes a lot of nifty new ways of configuring Discussions but otherwise is a direct port of the old view. 

Possibly the view is within the course authoring MFE but it wouldn't make sense to expose that new discussions configuration without the new MFE.

**Comment by Carlos-Muniz** [comment] 2022-05-31 17:23
@pdpinch Could you explain how Divided Discussion Topics are related here?

**Comment by kdmccormick** [comment] 2022-05-31 18:02
Could someone help me understand how this got fixed?

Why did Studio have a "Pages & Resources" menu item for @ziafazal , and what change was made to revert it back to the old "Pages" menu item?

**Comment by Carlos-Muniz** [comment] 2022-06-02 13:16
Closing this issue as the test case is no longer relevant: The Pages & Resource tab supplied by Course Authoring MFE and Discussions MFE has been replaced by the Pages tab which is supplied by a forum plugin(?).

**Comment by Carlos-Muniz** [comment] 2022-06-02 13:29
@BbrSofiane Can this be closed?

**Comment by kdmccormick** [comment] 2022-06-02 13:36
I agree that the issue seems fixed, but I'd like to understand how it was fixed before we close this and forget about it. A link to the PR that fixed it would be ideal.

**Comment by kdmccormick** [comment] 2022-06-06 17:48
We talked at the BTR meeting today -- @regisb had been messing with Waffle flags earlier and figures that he probably just accidentally enabled a flag that caused this issue :)

Since nutmeg.demo.overhangio.io has been reset since then, and this issue hasn't come back, I think it's safe to say that this is not going to be an issue in the base Nutmeg installation.

**Closed by kdmccormick** 2022-06-06 17:48 UTC
Labels: nutmeg testing
