### ISSUE TITLE
TC_AUTHOR_45 > Studio > Unit > Some advance X blocks are giving error in studio

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#159] opened 2022-04-27 07:35 UTC
**Steps to reproduce:**

1. Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
2. Go to any course and add these units      a) Custom JavaScript Display and Grading b)  Custom Python-Evaluated Input.    c) Problem with Adaptive Hint
3. Check errors

**Expected result:**
All x blocks should be added successfully
**Actual result:**
Getting errors on mentioned x blocks

**Image:** 
<img width="1679" alt="Screenshot at Apr 27 12-27-12" src="https://user-images.githubusercontent.com/55684124/165465966-88f7ea4b-f72e-4157-b7fd-7d2f0ea61a55.png">

**Comment by fayyazahmed66** [comment] 2022-04-27 07:35
"label: nutmeg testing"

**Comment by DeanJayMathew** [comment] 2022-04-27 10:44
label: nutmeg testing

**Comment by DeanJayMathew** [comment] 2022-04-27 10:44
label: affects:nutmeg

**Comment by DeanJayMathew** [comment] 2022-04-27 10:44
label: type:bug

**Comment by mariajgrimaldi** [comment] 2022-05-13 20:45
Hi, I think some of those issues have something to do with the tutor codejail plugin, which doesn't have support for Nutmeg yet. We (eduNEXT) are working on it!

**Comment by BbrSofiane** [comment] 2022-05-23 12:48
Hi @mariajgrimaldi, is there someone we can assign this to? I guess the task would be to:
1. report here when the plugin is ready so it can be installed on the demo instance and then 
2. Test that the issue is fixed

**Comment by BbrSofiane** [comment] 2022-05-23 15:15
PR: eduNEXT/tutor-contrib-codejail#18

**Comment by mariajgrimaldi** [comment] 2022-05-30 19:16
PR for nutmeg-demo support: https://github.com/overhangio/nutmeg-demo/pull/15

**Comment by mariajgrimaldi** [comment] 2022-05-31 17:15
Hello there, @regisb, hope you're well. When can we deploy the new changes to nutmeg-demo so we can test if this works?

**Comment by regisb** [comment] 2022-06-03 09:52
The codejail plugin was deployed on Monday as part of the latest run: https://github.com/overhangio/nutmeg-demo/runs/6660828918?check_suite_focus=true

**Comment by mariajgrimaldi** [comment] 2022-06-03 13:49
I'll be testing this then! Thank you so much @regisb

**Comment by mariajgrimaldi** [comment] 2022-06-03 21:37
Hello there! I've just tested this and got these results:

![image](https://user-images.githubusercontent.com/64440265/171955429-c78f42d8-cfd1-4d27-8bb3-2742bc5d8573.png)
![image](https://user-images.githubusercontent.com/64440265/171955476-b5bcc142-b783-4565-b21a-6463e21638f6.png)
![image](https://user-images.githubusercontent.com/64440265/171955503-f63cef6d-d2dc-4e54-a608-446746bf7869.png)

I think we're getting this error:

**Problem with Adaptive Hint**
`cannot create LoncapaProblem block-v1:edX+DemoX+Demo_Course+type@problem+block@b77fe2dc33644e2491c526ae413de497: Error while executing script code: Couldn&#39;t execute jailed code: stdout: b&#39;&#39;, stderr: b&#39;Traceback (most recent call last):\n  File &#34;jailed_code&#34;, line 19, in &lt;module&gt;\n    exec(code, g_dict)\n  File &#34;&lt;string&gt;&#34;, line 67\n    print expect, ans\n          ^\nSyntaxError: Missing parentheses in call to \&#39;print\&#39;. Did you mean print(expect, ans)?\n&#39; with status code: 1. For more information check Codejail Service logs.`

Might be because of the problem template:
https://github.com/openedx/edx-platform/blob/master/common/lib/xmodule/xmodule/templates/problem/problem_with_hint.yaml

**Comment by regisb** [comment] 2022-06-06 07:21
> Should we update the template?

We most probably should :)

**Comment by angonz** [comment] 2022-06-06 11:32
Hi all,
Is the codejail plugin working in K8s? I've been testing and couldn't make it work. There's been an [incipient discussion](https://discuss.overhang.io/t/edunext-codejail-tutor-plugin/2736) and I've been investigating the [daemonset option](https://github.com/kubernetes/kubernetes/tree/master/test/images/apparmor-loader) as recommended in the [K8s docs](https://kubernetes.io/docs/tutorials/security/apparmor/#setting-up-nodes-with-profiles) without success yet.

**Comment by mariajgrimaldi** [comment] 2022-06-06 14:58
Then I'm on it @regisb.

Hello there @angonz! Can you open an issue in the codejail plugin repo? I'll tag the team that maintains our k8s installations so they can help you out!

**Comment by MoisesGSalas** [comment] 2022-06-06 15:33
Hi @angonz, would mind telling which part is not working for you? (the service as a whole or the profile enforcement?).

Applying the apparmor profile onto the nodes of a managed Kubernetes service is a challenge we are currently facing and we don't have a good solution at the moment.

P.S. You can test the service without specifying the apparmor profile by deleting the `container.apparmor.security.beta.kubernetes.io/codejailservice: "localhost/docker-edx-sandbox"` annotation.

**Comment by mariajgrimaldi** [comment] 2022-06-14 16:06
PR fixing template in the nutmeg release: https://github.com/openedx/edx-platform/pull/30570

**Comment by mariajgrimaldi** [comment] 2022-06-24 13:36
I believe we can close this issue after this PR is reviewed and merged: https://github.com/overhangio/tutor/pull/698

**Closed** 2022-06-27 07:20 UTC
Labels: type:bug, affects:nutmeg, nutmeg testing
