### ISSUE TITLE
Support for the Learning MFE

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#81] opened 2021-06-07 15:44 UTC
### Description

Coordinate, and if necessary execute, the tasks necessary to get the [Learning ](https://github.com/edx/frontend-app-learning) MFE up to speed for Maple.

### Acceptance Criteria

The Learning MFE should:

1. Work as intended with the rest of the Maple codebase.
2. Pass a minimum standard of documentation: at the very least, the READMEs should have descriptive text that includes use cases, screenshots, and particularly, documentation on that MFE's environment variables.
3. Be internationalized (i18n), localizable (l10n), and pass minimum accessibility (a11y) standards.
4. Be deployable via Tutor as a plugin.
5. It has a header and footer that are customizable via npm aliases: https://edx.readthedocs.io/projects/edx-developer-docs/en/latest/developers_guide/micro_frontends_in_open_edx.html#overriding-brand-specific-elements
6. It is compatible with the @edx/brand system: https://open-edx-proposals.readthedocs.io/en/latest/oep-0048-brand-customization.html
7. It uses CSS utility classes in a branding-friendly way. (i.e., don't use things like 'bg-white')

### Wishlist

The following is a collection of what the community has expressed interest in.  Any single item may be "upgraded" to the Acceptance Criteria above, pending discussion.

* The MFE should support path-based routing (added by @pdpinch)

**Comment by pdpinch** [comment] 2021-07-19 16:24
Path-based routing doesn't appear to be implemented in the learning MFE. Is that a requirement for Maple?

**Comment by pdpinch** [comment] 2021-07-20 14:17
Our findings so far:

- If you use domain-based routing, you will need to add the MFE domains to `CORS_ORIGIN_WHITELIST` and, possibly, `CSRF_TRUSTED_ORIGINS`
- MFE Authentication requires the full complement of JWT settings. Since the individual settings aren't documented, we're not sure what these are for and how they interact with the MFE.

**Comment by arbrandes** [comment] 2021-07-20 17:07
@cmltaWt0, since you did such a great job on the ecommerce MFEs, would you be interested in investigating what needs to be done to get the learning MFE up and running on current master?

At this point we're mostly interested in how easy/difficult it would be just to get it working.  We're not after a PR to edx/configuration, for instance.  (The end goal would actually be a PR to Tutor, when/if we get there.)

**Comment by nedbat** [comment] 2021-07-20 18:18
Can we have some more specifics for "reasonably themeable"? Are the current Lilac MFE's reasonably themeable?

**Comment by arbrandes** [comment] 2021-07-20 19:15
@nedbat, good question.  IIRC, this line comes from when we were discussing what to do about the MFEs we would support for Lilac - before we found out how hard theming would be.  As far as I'm concerned, we can ditch that line.  (Possibly in favor of a dedicated issue to keep track of theming developments.  #36 would be a good start, for instance.)

**Comment by cmltaWt0** [comment] 2021-07-23 15:28
> @cmltaWt0, since you did such a great job on the ecommerce MFEs, would you be interested in investigating what needs to be done to get the learning MFE up and running on current master?
> 
> At this point we're mostly interested in how easy/difficult it would be just to get it working. We're not after a PR to edx/configuration, for instance. (The end goal would actually be a PR to Tutor, when/if we get there.)

Yeap. I think it's reasonable (not such reasonable as `reasonably themeable` but anyway :) )

I'll participate in this investigation.

**Comment by pdpinch** [comment] 2021-07-26 15:40
There are four .env settings in frontend-app-learning for logos. What are they for? Is it possible to annotate these similar to other settings?

from https://github.com/edx/frontend-app-learning/blob/a003059c8f70fc8371d0ef22a83b0bad2ca23f4f/.env#L15-L18

LOGO_URL=''
LOGO_TRADEMARK_URL=''
LOGO_WHITE_URL=''
FAVICON_URL=''

**Comment by jmyatt** [comment] 2021-07-26 19:37
@pdpinch does this now-merged OSPR address your question on subpath hosting? https://openedx.atlassian.net/browse/OSPR-5847

**Comment by pdpinch** [comment] 2021-08-03 21:32
Thanks for the link @jmyatt. I think that commit was necessary for other MFEs to work, but frontend-app-learning is still missing the basic support.

**Comment by mikix** [comment] 2021-08-05 20:41
Those four variables are mentioned in the general MFE developer docs:
https://edx.readthedocs.io/projects/edx-developer-docs/en/latest/developers_guide/micro_frontends_in_open_edx.html#branding

**Comment by pdpinch** [comment] 2021-08-11 20:27
FYI, we're starting work on making frontend-app-learning support path-based routing like the other MFEs.

**Comment by mikix** [comment] 2021-08-24 18:06
> This is probably out-of-scope, but we used to use the old theming system to override the items in the user menu. Is there a best practice way to do that with MFEs?

The way I know to theme frontends is to extend the default theme and use your new custom theme. This repo's readme has instructions: https://github.com/edx/brand-openedx

Is that what you meant?

**Comment by regisb** [comment] 2021-09-09 10:10
Looks like the learning MFE is working in Tutor :)

![tutor learning](https://user-images.githubusercontent.com/44319/132666998-cab4fad4-ed7c-42a6-aef9-dd5a61637b4d.png)

I am currently working on getting Tutor to run with the Open edX master branches; the result will be available in the "edge" branches of the [tutor main repo](https://github.com/overhangio/tutor/) and the [mfe plugin](https://github.com/overhangio/tutor-mfe).

That's it! I just wanted to share this small achievement :-)

**Comment by pdpinch** [comment] 2021-09-14 14:00
@regisb how are you handling the routing in Tutor? (I should look and see for myself, but I thought I'd ask if it's a quick question)

**Comment by regisb** [comment] 2021-09-14 14:28
> how are you handling the routing in Tutor? 

Traffic first goes through Caddy (for SSL termination), then Nginx (for proxying), then another Caddy server (in the MFE container). The MFE container holds all the static assets for all microfrontends. The Caddy server in this MFE container serves static assets from multiple directory locations. Here is the Caddy configuration file: https://github.com/overhangio/tutor-mfe/blob/master/tutormfe/templates/mfe/build/mfe/Caddyfile The following values are added to the LMS settings: https://github.com/overhangio/tutor-mfe/blob/master/tutormfe/patches/openedx-lms-production-settings

Does that answer your question?

**Comment by BbrSofiane** [comment] 2021-09-27 15:26
https://discuss.overhang.io/t/running-open-edx-on-master-with-tutor-edge/1957/4

**Comment by davidjoy** [comment] 2021-09-27 16:00
FYI, the learning MFE has a hard-coded header and doesn't use the npm aliases mechanism described here: https://edx.readthedocs.io/projects/edx-developer-docs/en/latest/developers_guide/micro_frontends_in_open_edx.html#overriding-brand-specific-elements

This means that the header will be brandable (change styling), but not override-able (change functionality) today.

**Comment by pdpinch** [comment] 2021-09-27 16:08
@davidjoy do you know what would be involved in making the header (and footer) override-able? Is that something that could be fixed in an OSPR?

**Comment by davidjoy** [comment] 2021-09-27 16:29
Yes... I think we could.  It might be a smidge complicated.

I think the right thing to do is to move a basic, generic version of the header in the learning MFE into the frontend-component-header repository and export it from there as something like `LearningHeader` as a peer of the `Header` export.  Then give the MFE a dependency on that and pull the code from it instead.  Before we could merge the PR in the learning MFE, we'd also need to copy that code into `frontend-component-header-edx` so that edx.org's build process doesn't explode, since the site runs on `master`.  Then the two headers could diverge from there as needed.  

In the future, we could also add other headers (like `StudioHeader`) into frontend-component-header.

**Comment by regisb** [comment] 2021-09-27 19:59
@davidjoy I did not dig deep enough into the MFE source code to fully understand your explanations above; nonetheless, the process seems rather complex for a task that is a frequent requirement of most Open edX operators. Is there any way to improve and document the theming of MFEs to tell our users a better story?

**Comment by davidjoy** [comment] 2021-09-29 18:47
This task would be a one-time refactor of the code in the learning MFE that would enable operators to make their own customized versions of the header.  The existing mechanism for doing that is to use an npm alias to point `@edx/frontend-component-header` to `my-frontend-component-header` - the problem is that the learning MFE just doesn't get its header from that package today; it's hardcoded in the app.  

The process of using the npm alias is described here: https://edx.readthedocs.io/projects/edx-developer-docs/en/latest/developers_guide/micro_frontends_in_open_edx.html#overriding-brand-specific-elements

**Comment by cmltaWt0** [comment] 2021-10-05 14:31
As far as I understand the same architecture as for [frontend-app-ecommerce](https://github.com/edx/frontend-app-ecommerce/blob/master/src/index.jsx#L26) should be applied.
![image](https://user-images.githubusercontent.com/877401/136043489-71f4bd0b-854b-4ca9-9c08-15f7b01fb41c.png)

**Comment by davidjoy** [comment] 2021-10-05 18:00
Yup - it should be very similar.  I think line 1 of index.jsx ends up looking like: 

```
import LearningHeader, { messages as headerMessages } from '@edx/frontend-component-header';
```

... for instance, since we'll need to move the existing header into that repo and then use it.

**Comment by cmltaWt0** [comment] 2021-10-06 11:08
@regisb 
I'm doing some testing for learning MFE on local tutor installation (non production mode).

And I've encountered missing waffle flag in hooks for lms.
Added in [PR](https://github.com/overhangio/tutor-mfe/pull/11).

Next we could discuss the following flags to add:
```
course_home.course_home_mfe (REQUIRED FOR FOLLOWING FLAGS)
course_home.course_home_mfe_dates_tab (OPTIONAL)
course_home.course_home_mfe_outline_tab(OPTIONAL)
course_home.course_home_mfe_progress_tab(OPTIONAL)
```

Also I can't get the fully working learning app - it still stuck in Loading state (deployed from nightly branches from scratch).
I'll play around to apply my previous fixes or we can meet to resolve it more quickly because I don't understand how it's working for you.

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/877401/136190978-ec1f3a55-129d-43f5-bc47-a22aef799202.png">


Next steps:
- find out the fix for infinite loading on local tutor installation
- test production mode
- test forked learning app repo to apply shared Header and Footer as a npm packages
- create a PR to learning app repo

**Comment by jmyatt** [comment] 2021-10-06 13:23
@cmltaWt0 about the flags you mentioned, only `course_home.course_home_mfe_progress_tab` should still be relevant.

Removal of `course_home.course_home_mfe_dates_tab` and `course_home.course_home_mfe_outline_tab` was done [in this commit](https://github.com/edx/edx-platform/commit/87e3ce69b6db3b93d64678f46926d4e431817f2c#diff-69936e1a963cf5b81fd008890439a3ece0d241a488fe56e45df70cac5e0b55c0L24-L27)

Removal of `course_home.course_home_mfe` was done [in this commit](https://github.com/edx/edx-platform/commit/e645d11bba714a498d53fbd1a4ef9f9f851065b3#diff-69936e1a963cf5b81fd008890439a3ece0d241a488fe56e45df70cac5e0b55c0L22)

**Comment by cmltaWt0** [comment] 2021-10-06 20:00
Thanks @jmyatt !
I miss that nighty is still on lilac.2 by default.

@regisb It's my fault with flag in tutor-mfe's PR. 
New courseware was enabled by default in https://github.com/edx/edx-platform/pull/27757

I have to revert the PR (it makes no effect on the logic).

**Comment by asadiqbal08** [comment] 2021-10-07 08:55
> Yes... I think we could. It might be a smidge complicated.
> 
> I think the right thing to do is to move a basic, generic version of the header in the learning MFE into the frontend-component-header repository and export it from there as something like `LearningHeader` as a peer of the `Header` export. Then give the MFE a dependency on that and pull the code from it instead. Before we could merge the PR in the learning MFE, we'd also need to copy that code into `frontend-component-header-edx` so that edx.org's build process doesn't explode, since the site runs on `master`. Then the two headers could diverge from there as needed.
> 
> In the future, we could also add other headers (like `StudioHeader`) into frontend-component-header, which could then be used in MFEs like frontend-app-course-authoring.

@davidjoy related to the suggestion above, Can you please take a look over the [approach here](https://github.com/mitodl/mitxonline/issues/252) ?

**Comment by cmltaWt0** [comment] 2021-10-08 13:57
@davidjoy Could you support me in the comment above by pointing a person to ask for the list of features or it's simpler to create an issue in the learning repo?

**Comment by asadiqbal08** [comment] 2021-10-13 07:05
> > Yes... I think we could. It might be a smidge complicated.
> > I think the right thing to do is to move a basic, generic version of the header in the learning MFE into the frontend-component-header repository and export it from there as something like `LearningHeader` as a peer of the `Header` export. Then give the MFE a dependency on that and pull the code from it instead. Before we could merge the PR in the learning MFE, we'd also need to copy that code into `frontend-component-header-edx` so that edx.org's build process doesn't explode, since the site runs on `master`. Then the two headers could diverge from there as needed.
> > In the future, we could also add other headers (like `StudioHeader`) into frontend-component-header, which could then be used in MFEs like frontend-app-course-authoring.
> 
> @davidjoy related to the suggestion above, Can you please take a look over the [approach here](https://github.com/mitodl/mitxonline/issues/252) ?

@davidjoy ⏫

**Closed** 2021-12-29 18:18 UTC
Labels: priority:high, type:btr-task

**Comment by rahulkg666** [comment] 2023-10-10 17:39
hi

**Comment by rahulkg666** [comment] 2023-10-10 17:40
Hi I need to know how can I add copy protection in mfe learning app

**Comment by kdmccormick** [comment] 2023-10-10 18:57
Hi @rahulkg666 . This is not the right place to ask for help. Please use [the forums](https://discuss.openedx.org/) instead.
