### ISSUE TITLE
TC_LEARNER_32 > LMS > Tabs > wiki page is not visible

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#173] opened 2022-05-09 10:46 UTC
**Steps to reproduce:**

1. Go to https://apps.nutmeg.demo.overhang.io/learning/course/ with valid user credentials
2. Check course tabs
**Expected result:**
All mentioned tabs should be visible.
**Actual result:**
Wiki tab is not present

**Comment by fayyazahmed66** [comment] 2022-05-09 10:46
label: nutmeg testing

**Comment by mtyaka** [comment] 2022-05-24 08:41
I don't think this is a bug. It looks like the wiki is disabled by default.

You can enable it from the Studio on the "Content -> Pages" page by clicking the show/hide icon.

**Comment by pdpinch** [comment] 2022-05-24 10:57
“Pages and resources” is a feature of the course authoring MFE. 

As far as I know, the wiki hasn’t been deprecated in any way, so this must be some kind of regression.

**Comment by regisb** [comment] 2022-05-25 11:05
That's great @xitij2000, thanks a lot. How do you think we should address this? Should we restore the static course tabs in the page and resources view?

**Comment by pdpinch** [comment] 2022-05-25 12:48
@xitij2000 this change should have been mentioned in the [Open edX Release Planning page for Nutmeg](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3205201949/Nutmeg). However we work this out, I'll need to add some information to the [release notes PR](https://github.com/openedx/edx-documentation/pull/2056).

**Comment by DeanJayMathew** [comment] 2022-05-26 05:50
@fayyazahmed66 @mtyaka  @regisb @pdpinch @xitij2000

I am trying to access the **Pages and Resources** tab in Studio and I'm getting an error.

Steps to reproduce:

1. Click Content > Pages and Resources:
<img width="715" alt="Screen Shot 2022-05-26 at 06 43 41" src="https://user-images.githubusercontent.com/9986523/170424922-d0f73a64-98d6-4dd7-8b52-2952bba58017.png">


2. You will see this error Page Not Found:

<img width="1440" alt="Screen Shot 2022-05-26 at 06 43 31" src="https://user-images.githubusercontent.com/9986523/170424980-2955dd28-db5e-4201-a4b0-07b98adef669.png">

**Comment by xitij2000** [comment] 2022-05-26 12:10
@DeanJayMathew I think you might need to configure the course authoring MFE for that link to work. So it does seem like the course authoring MFE is no longer optional.

**Comment by xitij2000** [comment] 2022-05-26 12:23
> That's great @xitij2000, thanks a lot. How do you think we should address this? Should we restore the static course tabs in the page and resources view?

It might be worth looking into any other functionality that might have moved to the course authoring MFE. I worked on that MFE a lot, and AFAIK other than the wiki nothing should be missing from the legacy UI, so reverting that change might address this till the point that the course authoring MFE is no longer optional.

**Comment by regisb** [comment] 2022-05-30 13:15
Thanks for your insights @xitij2000. IMHO the pages and resource tab should default to the previous behaviour when the course authoring MFE is not enabled.

**Comment by xitij2000** [comment] 2022-06-01 07:26
> Thanks for your insights @xitij2000. IMHO the pages and resource tab should default to the previous behaviour when the course authoring MFE is not enabled.

I've added a task into the next sprint (starting 14th June) to look into this. Do tell if that timeline doesn't work here and if more urgency is needed. I'll try to shuffle things around in that case.

**Comment by DeanJayMathew** [comment] 2022-06-01 07:46
Hi @xitij2000

Just fyi Nutmeg will be released on June 9th, but since the MFEs are not
supported until Olive I don't see a reason to rush it... but I stand
corrected.

Best.


Dean Jay Mathew
Director, ABC Online Courses Limited

Trusted Open edX® Service Providers since 2015
Schedule a meeting with me: https://calendly.com/abconlinecourses
View Our Website <http://www.abconlinecourses.com>
WhatsApp: +447379424911 (UK)
Registered Address: Chestnut House
***@***.***,-2.1459131,15z/data=!3m1!4b1!4m8!1m2!2m1!1schestnut+house+53d+beanacre+sn127py!3m4!1s0x48717c9105a9d3d7:0x15804f821ad57207!8m2!3d51.3980641!4d-2.1374675>
(Wiltshire, England, UK)



*Legal Disclaimer: **This email and any files transmitted with it are
confidential and intended solely for the use of the individual or entity to
whom they are addressed and intended. If you have received this email in
error please notify the sender or system manager immediately. This message
contains confidential information and is intended only for the individual
named. If you are not the named addressee you should not disseminate,
distribute or copy this e-mail. Please notify the sender immediately by
e-mail if you have received this e-mail by mistake and delete this e-mail
from your system. If you are not the intended recipient you are notified
that disclosing, copying, distributing or taking any action in reliance on
the contents of this information is strictly prohibited.*

**Comment by regisb** [comment] 2022-06-03 08:43
I do think that this issue is rather pressing and we should strive to fix it before June 9th. The course pages are an important feature of Open edX and we can't really ship Nutmeg without them (IMHO).

**Comment by DeanJayMathew** [comment] 2022-06-03 08:51
Agree with @regisb of course. His idea above of "the pages and resource tab should default to the previous behaviour when the course authoring MFE is not enabled" is it possible to fix in the next week (before 9th June) @xitij2000?

**Comment by xitij2000** [comment] 2022-06-03 08:54
@regisb @DeanJayMathew I will prioritize the work accordingly and try my best to get it ready before then.

**Comment by BbrSofiane** [comment] 2022-06-06 16:13
@xitij2000 Any updates on this issue?

**Comment by xitij2000** [comment] 2022-06-07 06:26
> @xitij2000 Any updates on this issue?

I've just created a PR for this: https://github.com/openedx/edx-platform/pull/30550

**Comment by regisb** [comment] 2022-06-09 08:24
Thanks a lot for working on this @xitij2000! Your PR will be cherry-picked in the default openedx Docker image that ships with Tutor in Nutmeg, even if it's not merged in time.

**Comment by NeOneSoft** [comment] 2022-08-05 13:50
Hi @xitij2000 hope you doing well!!!do you have any update regarding this issue?. Please let us know in case you need help.Thanks a lot!!

**Comment by xitij2000** [comment] 2022-08-05 14:09
> Hi @xitij2000 hope you doing well!!!do you have any update regarding this issue?. Please let us know in case you need help.Thanks a lot!!

Sorry for losing track of this. I believe this issue is fixed now given that the above PR is merged. Are you still facing the issue?

**Comment by NeOneSoft** [comment] 2022-08-05 15:30
Thank you so much @xitij2000!! I only was taking a look on this in order to close it so I think that we can do it if we don't have any other concern.

**Comment by BbrSofiane** [comment] 2022-08-09 20:32
The fix has been cherry-picked in tutor:
- Fix: https://github.com/open-craft/edx-platform/commit/3d54f284f82b61e693ad652d8d6e46a226fcb36d
- Cherry-pick: https://github.com/overhangio/tutor/blob/c4388e134ca4bf1961b9906dd3fb8600d197f7a5/tutor/templates/build/openedx/Dockerfile#L52

**Closed by BbrSofiane** 2022-08-09 20:32 UTC
Labels: priority:high, nutmeg testing
