### ISSUE TITLE
The student onboarding screen includes a hardcoded mention to edX in the learning MFE

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#175] opened 2022-05-10 10:58 UTC
When signing up as a new user in the LMS, we are presented with an onboarding screen which includes a hardcoded mention of "edX". See the screenshot below.

![Screenshot from 2022-05-10 12-16-09](https://user-images.githubusercontent.com/44319/167613111-d6dbb0ab-56a8-4bd5-90b1-cdb376e0ee37.png)

FYI this issue was detected during a live stream: https://www.youtube.com/watch?v=28_lt90UREo (at about 1:58:00).

**Comment by mariajgrimaldi** [comment] 2022-05-13 20:23
Hi! I believe [this issue](https://github.com/openedx/frontend-app-learning/pull/945) fixes that! Who should we mention?

**Comment by BbrSofiane** [comment] 2022-05-18 11:24
Approved and merged.

**Comment by BbrSofiane** [comment] 2022-05-18 12:53
Can someone backport it to nutmeg?

**Comment by mariajgrimaldi** [comment] 2022-05-18 14:44
@BbrSofiane we're working on it!

**Comment by mariajgrimaldi** [comment] 2022-05-18 14:52
Here's the backport: https://github.com/openedx/frontend-app-learning/pull/947

**Comment by BbrSofiane** [comment] 2022-05-18 14:52
I've merged it

**Comment by BbrSofiane** [comment] 2022-05-23 12:44
Can someone confirm that the issue is fixed on the demo instance?

**Comment by mariajgrimaldi** [comment] 2022-05-23 12:47
I'll do it! @BbrSofiane

**Comment by regisb** [comment] 2022-05-23 12:54
We almost certainly have to re-build the MFE image on the server to pick up the latest changes. I'm doing it right now.

**Comment by mariajgrimaldi** [comment] 2022-05-24 12:52
It's working now!
![image](https://user-images.githubusercontent.com/64440265/170039155-d726fb97-13bc-44ad-8eef-d7eff4813abd.png)
We can close this :smile:

**Closed** 2022-05-24 14:38 UTC
Labels: affects:nutmeg, nutmeg testing
