### ISSUE TITLE
The authn MFE cookie banner includes hardcoded references to edX

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#240] opened 2022-12-09 22:01 UTC
When the authn MFE is enabled, the login page includes a cookie banner. Here is an excerpt from the demo platform: https://apps.olive.demo.overhang.io/authn/login?next=%2F

![image](https://user-images.githubusercontent.com/44319/206802265-ac11ce57-e91a-4e52-bb0d-a381e5a1da12.png)

Notice the cookie banner at the top: "edX and its Members use cookies and other tracking technologies for performance, analytics, and marketing purposes. By using this website, you accept this use. Learn more about these technologies in the [Privacy Policy](https://edx.org/edx-privacy-policy)."

These hardcoded references to edX are not usable outside of edX.org.

This cookie banner comes from the frontend-component-cookie-policy-banner package: 

https://www.npmjs.com/package/@edx/frontend-component-cookie-policy-banner
https://github.com/openedx/frontend-component-cookie-policy-banner

As we can see, we cannot override this text with a simple setting: https://github.com/openedx/frontend-component-cookie-policy-banner/blob/7f9bcd548a0264e068d36308c3b97713579fc229/src/constants.js#L51

### PRs

- [ ] https://github.com/openedx/frontend-component-cookie-policy-banner/pull/412

**Comment by arbrandes** [comment] 2022-12-12 11:34
Just an FYI that there is [a tentative PR](https://github.com/openedx/frontend-component-cookie-policy-banner/pull/412), but it doesn't do what we need, and I haven't heard back from the author in a few days.

**Comment by arbrandes** [comment] 2022-12-12 11:37
Actually, this is a duplicate of #146.

**Closed by arbrandes** 2022-12-12 11:37 UTC
Labels: bug, release testing
