### ISSUE TITLE
Bulk email templates contains many edX-specific reference (and are thus unusable)

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#100] opened 2021-09-07 14:46 UTC
Emails sent via the Bulk Email feature use an edX specific template.

More details in overhangio/tutor#485

**Comment by cmltaWt0** [comment] 2021-09-07 20:07
And here we need to design this email template firstly for  `open edX` brand.
Do we have an open edX brand-book already (maybe I miss it somewhere)?

**Comment by regisb** [comment] 2021-11-25 14:47
Hi @mdbc-tech! Any news on this?

**Comment by clemente** [comment] 2021-12-31 15:35
@mdbc-tech Hi, could you post the status of the task, some work in progress or what's left to do? Thanks

**Comment by ziafazal** [comment] 2022-01-07 14:27
@regisb @BbrSofiane @clemente  can I pick this up if original assignee is no longer available to look into this issue?

**Comment by regisb** [comment] 2022-01-07 15:59
YES!!! :heart::heart: :heart:

**Comment by ziafazal** [comment] 2022-01-10 06:39
> YES!!! ❤️❤️ ❤️

It appears I can't assigne it to myself. Can you assigne it to me?

**Comment by ziafazal** [comment] 2022-01-11 08:44
@regisb I have investigated this issue. It appears we can override both HTML and Text version of Bulk Email temples from django admin(`Home › Bulk_Email › Course email templates ›`). All we need to do is set `Name` field of the template empty. Attached screen shot
<img width="1371" alt="Screen Shot 2022-01-11 at 1 36 06 PM" src="https://user-images.githubusercontent.com/434995/148909665-9d1c88c6-74de-4bc8-9989-7b5608105c93.png">

**Comment by regisb** [comment] 2022-01-17 10:22
>  All we need to do is set Name field of the template empty.

What happens when you do this? Does it prevent course emails from being themed at all?

We need to provide users a way to have themed text/html course emails that correspond to their visual identity out of the box. Maybe that the solution requires a change in Tutor, but I suspect that we also need to create new templates that will automatically load static assets from the LMS.

**Comment by ziafazal** [comment] 2022-01-24 13:02
Setting Name filed empty means value of  **Plain template** and **Html Template** fields will be used as Text and Html templates of course emails.

To theme course email users need to put their own templates in  **Plain template** and **Html Template** fields and set **Name** field empty. That way users can override default course email templates.

**Comment by ziafazal** [comment] 2022-02-02 08:47
@regisb what are next step on this?

**Comment by regisb** [comment] 2022-02-03 08:08
@ziafazal you are right that when we create a custom template and set "Name" to an empty field then that template is used to send emails. The problem is that all users need to create a template that corresponds to their identity. Open edX should ship with a template that works for everyone out of the box. So the next steps would be:

1. Create a new template that works for everybody.
2. Make that template the default out of the box.

**Comment by ziafazal** [comment] 2022-03-04 05:38
@BbrSofiane how I can move this issue in `In progress` column?

**Comment by ziafazal** [comment] 2022-03-15 13:35
@regisb @BbrSofiane should we mark this issue as fixed since the PR which provides ability to send bulk course emails via edx-ace got merged?

**Comment by regisb** [comment] 2022-03-28 07:38
Hey @ziafazal thanks for your work. Does your PR mean that it is enough to set `BULK_EMAIL_SEND_USING_EDX_ACE = True` on a vanilla Open edX installation to get rid of the edX theming?

Concerning your PR: I realise that I should have commented there but it flew under my radar. I think that you should create a good default for the `BULK_EMAIL_SEND_USING_EDX_ACE` in lms/envs/common.py and document the setting such that it appears in https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/

**Comment by ziafazal** [comment] 2022-03-28 07:54
@regisb yes setting `BULK_EMAIL_SEND_USING_EDX_ACE` to `True` would send emails via edx-ace and it will use default theming being used for all edx-ace based emails.

`BULK_EMAIL_SEND_USING_EDX_ACE` setting toggle is already in the docs 
https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/featuretoggles.html#featuretoggle-BULK_EMAIL_SEND_USING_EDX_ACE

Its default value is `False`.

**Comment by regisb** [comment] 2022-03-28 08:57
Awesome! Thanks for the quick answer. To close this, I opened the following PR that adds the setting to the default installation in Tutor: https://github.com/overhangio/tutor/pull/621

**Closed** 2022-05-23 12:33 UTC
Labels: type:bug, affects:lilac, priority:medium, affects:maple
